### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by hungeraibin** [hungeraibin/demos#2]
# CSS
## 1. 两种盒模型分别说一下
- content-box：内容
- border-box：内容区 + 内边距 + 边框 
- box-sizing 为 bodrer-box 写起来更方便

## 2. 如何垂直居中？

1.flex 
```css
display: flex;
justify-content: center;
align-items: center;
```
2. translate -50%
```css
position: absolute;
top: 50%;
left: 50%;
transform: translate(-50%, -50%);
```
3. margin-top -50%
```css
width: 300px;
height 100px;
position: absolute;
top: 50%;
left: 50%;
margin-top: -50px;
margin-left: -150px;
```
4. margin auto
```css
position: absolute;
top: 0;
left: 0;
right: 0;
bottom: 0;
margin: auto;
```
5. table 自带居中
```html
  <table class="parent">
    <tr>
      <td class="child"></td>
    </tr>
```
6. display table
```css
div.table{
  display: table;
  border: 1px solid red;
  height: 600px;
}

div.tr{
  display: table-row;
}

div.td{
  display: table-cell;
  vertical-align: middle;
}
```
7. before after 加上 height 100% 的 inline-blick
```css
.child {
  display: inline-block;
  vertical-align: middle;
}
.parent:before {
  content: '';
  display: inline-block;
  height: 100%;
  vertical-align: middle;
}
```

## 3. flex 怎么用，常用属性有哪些？
- Flex 是 Flexible Box 的缩写，意为"弹性布局
```css
.box {
  display: flex;
}
```
- 常见的容器属性
1. flex-direction: row | row-reverse | column | column-reverse
2. flex-wrap: nowrap | wrap | wrap-reverse;
3. justify-content: flex-start | flex-end | center | space-between | space-around;
4. align-items: flex-start | flex-end | center | baseline | stretch;
- 常见的项目属性
1. order: 0
2. flex-grow: 0
3. flex-shrink:1
4. align-self: flex-start | flex-end | center | baseline | stretch;

## 4. BFC 是什么？
- 块级格式化上下文：独立的容器，内部元素不会影响到外面的元素
- 触发BFC
1. float 非none
2. position: absolute | fixed;
3. overflow: 非visible
4. display: inline-block | flex | table-cell
- 解决
1. 外边距合并
2. 清除浮动
3. 阻止被浮动元素覆盖

## 5. CSS 选择器优先级
- 行内 > ID > 类 = 属性 = 伪类(:hover) > 标签 = 伪元素(::before)
- 越具体优先级越高
- 写在后面的，覆盖写在前面的
- !important最高，少用
## 6. 清除浮动说一下
- .clearfix 加到容器上，里面的子元素的浮动就被清除了
```css
.clearfix::after {
  content: '';
  display: block | table;
  clear: both;
}
```
